### ISSUE TITLE
Context seems to reset on a pr page basis

### ISSUE THREAD

**Issue by kristianeboe** [manvalls/server-only-context#1]
I stumbeled over this little gem here https://stackoverflow.com/questions/74311376/using-react-context-with-nextjs13-server-side-components

Fits my use case exactly as I am trying to pass the locale around in my server components without prop drilling.

This works great when I set it in my root layout and access it there, in the page, and in sub components of that page.

However, on different pages it seems the serverContext resets to the default locale, "en". And even if I set the serverContext again in that child context, it doesn't seem to work.

Can you at least clarify wether setting the context in the root layout should in theory propagate it to all sup pages and sub layouts? Or is it expected that we need to set the context on each page/layout individually?

Thanks for your work!

**Comment by mnik01** [comment]
+1

**Comment by jdgamble555** [comment]
EDIT: I am completely wrong.  It seems `cache` in react does use a sort of context under the hood, so this is a good solution. You just have to import it correctly.

https://dev.to/jdgamble555/easy-context-in-react-server-components-rsc-1mdf

___
By defining the function, you're creating a global variable, which is accessible to all users instead of just the current one.  Hence, a memory leak.

This is no different than doing:

```ts
export const cache = new Map();
```

We don't want to create a global variable in node.js (or bun or deno), as it could be accessible to other users.  We need to create it inside the react instance itself.

Unfortunately, `createServerContext()` is getting depreciated, and `createContext` will not run on the server.  `cache` is not a fix for this.

J

**Comment by manvalls** [comment]
Hey, sorry, just seen this. It needs to be set per page.
